import {
    botCapPerUser,
    botConcurrentGameCap,
    guestRetryAfterSeconds,
    humanConcurrentGameCap,
    humanGameCooldownSeconds,
    liveGameListCap,
    minimumAge,
    nameMaxLength,
    nameMinLength,
    placementRadius,
    plural,
    siteName,
    unlimitedWallCapMs,
    type DiscordNames,
    type SignInFailure,
} from '@hexo-arena/contract';
import type { ReactNode } from 'react';
import { rich, type Slot } from './rich';

const wallCapHours = unlimitedWallCapMs / 3_600_000;

// A wait in whole minutes, as a rate and as a delay: "a minute" for one.
const perMinutes = (minutes: number) => (minutes === 1 ? `a minute` : `every ${String(minutes)} minutes`);
const inMinutes = (minutes: number) => (minutes === 1 ? `a minute` : `${String(minutes)} minutes`);
// A wait the server named, in seconds under a minute and whole minutes, rounded up, past it.
const inWait = (seconds: number) => (seconds < 60 ? `${String(seconds)} s` : inMinutes(Math.ceil(seconds / 60)));

/**
 * The words the web app shows, in English, grouped by screen and area.
 * Text the server also renders, from the site's name and tagline to page
 * titles, results, and clock words, lives in the contract instead.
 * Text with values in it is a function of those values, and text with
 * elements in it takes a {@link Slot} per element.
 * Limits and counts come from the contract's constants and its plural.
 */
export const en = {
    shell: {
        skipToContent: `Skip to content`,
        mainNav: `Main`,
        nav: {
            home: `Home`,
            play: `Play`,
            games: `Games`,
            ladder: `Ladder`,
            bots: `Bots`,
            build: `Build a bot`,
        },
        paused: `Starting games is paused; live games continue`,
        links: {
            build: `Build a bot`,
            credits: `Credits`,
            botApi: `Bot API`,
            imprint: `Impressum / Legal notice`,
            privacy: `Privacy`,
            terms: `Terms`,
            licenses: `Licenses`,
        },
        opensInNewTab: (label: string) => `${label}, opens in a new tab`,
        signIn: (provider: Slot): ReactNode => rich`Sign in${provider(` with Discord`)}`,
        // A no-break space holds "see Privacy." together, so the line never
        // ends on a word alone at any width or text size.
        trustLine: (privacy: Slot): ReactNode =>
            rich`Your email stays with Discord, and a first sign-in asks for your public name; see\u00a0${privacy(`Privacy`)}.`,
        guestTrustLine: (privacy: Slot): ReactNode =>
            rich`Signing in ends this guest session and its games. Your email stays with Discord; see\u00a0${privacy(`Privacy`)}.`,
        signInFailed: {
            unconfigured: () => `Sign-in is not set up on this server`,
            cancelled: () => `You cancelled the sign-in at Discord; nothing was kept`,
            expired: () => `That sign-in expired; sign in again`,
            rejected: () => `Discord did not confirm the sign-in; try again`,
            banned: (imprint: Slot): ReactNode => rich`This Discord account is banned from ${siteName}; the operator's contact is in the ${imprint(`Legal notice`)}`,
            busy: () => `Sign-in is busy right now; try again in a minute`,
        } satisfies Record<SignInFailure, (imprint: Slot) => ReactNode>,
        identity: {
            guestName: (name: string) => `${name}, unrated`,
            discord: ({ username, displayName }: DiscordNames) =>
                displayName === null ? `Discord: @${username}` : `Discord: ${displayName} (@${username})`,
            unrated: `unrated`,
            close: `Close menu`,
            rating: (spoken: Slot, value: ReactNode): ReactNode => rich`${spoken(`, rating `)}${value}`,
            profile: `Profile`,
            build: `Build a bot`,
            signOut: `Sign out`,
            signOutFailed: `Sign-out did not go through; you are still signed in`,
            endGuest: `End guest session`,
            endGuestNote: `Your guest games end with it.`,
            endGuestFailed: `The guest session did not end; try again`,
        },
    },
    player: {
        botBadge: `BOT`,
        online: `Online`,
        offline: `Offline`,
        open: `open`,
        closed: `closed`,
        provisional: `Provisional until the rating settles`,
        acceptsTurn: (min: number, max: number) => `turn ${String(min)} to ${String(max)} s`,
        acceptsMatch: `match`,
        acceptsUnlimited: `unlimited`,
        acceptsList: (parts: readonly string[]) => parts.join(`, `),
    },
    ladder: {
        title: `Ladder`,
        kinds: {
            all: `All`,
            bots: `Bots`,
            humans: `Humans`,
        },
        kindFilter: `Show`,
        failed: `The ladder did not load`,
        pulse: (
            ranked: number,
            kind: `all` | `bots` | `humans`,
            roster: { online: number; open: number } | null,
            strong: Slot,
            dot: ReactNode,
        ): ReactNode => {
            const nouns = { all: [`player`, `players`], bots: [`bot`, `bots`], humans: [`human`, `humans`] } as const;
            const count = rich`${strong(String(ranked))} ranked ${plural(ranked, nouns[kind][0], nouns[kind][1])}`;
            if (roster === null) return count;
            if (roster.online === 0) return rich`${count}; no bots online`;
            const open = roster.open === 0 ? `none` : strong(String(roster.open));
            return rich`${count}; ${dot}${strong(String(roster.online))} ${plural(roster.online, `bot`, `bots`)} online, ${open} open for challenges`;
        },
        top: `Top of the ladder`,
        human: `Human`,
        by: (owner: ReactNode): ReactNode => rich`By ${owner}`,
        full: `Full ladder`,
        rank: `Rank`,
        player: `Player`,
        rating: `Rating`,
        you: `you`,
        note: `Players join the ladder once their rating is no longer provisional.`,
        empty: {
            heading: `No ranked players yet`,
            body: `A player joins the ladder once their rating is no longer provisional. ${siteName} runs no bots of its own; the ladder is whatever you bring.`,
            build: `Build a bot`,
            browse: `Browse bots`,
        },
        live: {
            title: `Live games`,
            all: `All live games`,
            failed: `Live games did not load; trying again shortly`,
            none: `No live games right now.`,
            watch: `Watch `,
            vs: `vs`,
            unrated: `unrated`,
            toMove: (name: ReactNode): ReactNode => rich`${name} to move`,
        },
    },
    bots: {
        title: `Bots`,
        build: `Build a bot`,
        onlineOnly: `Online only`,
        failed: `The bot list did not load`,
        bot: `Bot`,
        owner: `Owner`,
        challenges: `Challenges`,
        rating: `Rating`,
        accepts: `Accepts`,
        version: `Version`,
        playColumn: `Play`,
        noneOnline: `No bots online right now; clear Online only to see every bot.`,
        online: `Online`,
        offline: `Offline`,
        openKey: `open: takes challenges now`,
        provisionalKey: `?: provisional rating`,
        play: `Play`,
        playBot: (name: string) => `Play ${name}`,
        busy: `In ${String(botConcurrentGameCap)} ${plural(botConcurrentGameCap, `game`, `games`)}`,
        empty: {
            heading: `No bots yet`,
            body: `${siteName} runs no bots of its own; build the first one.`,
            build: `Build a bot`,
        },
    },
    home: {
        title: `Play HeXO`,
        rules: `Six in a row wins; each turn places two stones.`,
        playBot: `Play a bot`,
        noneOnline: `No bots online right now`,
        noBots: `${siteName} runs no bots of its own; the ladder is whatever you bring.`,
        build: `Build a bot`,
        lastGame: (game: Slot, x: string, o: string, result: string): ReactNode => rich`Last game: ${game(`${x} vs ${o}`)}; ${result}`,
        yourGames: `Your games`,
        against: (name: string) => `Against ${name}`,
        yourTurn: `Your turn`,
        toMove: (name: string) => `${name} to move`,
        featured: `Featured game`,
        watch: (x: string, o: string) => `Watch ${x} vs ${o}`,
        ended: `Just finished`,
        last: `Last game`,
        replay: (x: string, o: string) => `Replay ${x} vs ${o}`,
        liveNow: `Live now`,
        allLive: `All live games`,
        ladder: `Ladder`,
        fullLadder: `Full ladder`,
        settling: `Settling ratings`,
        settlingNote: `No ranked players yet; a player joins the ladder once their rating is no longer provisional.`,
        recent: `Recent results`,
        finishedAgo: (seconds: number) => {
            if (seconds < 60) return `just now`;
            if (seconds < 3_600) return `${String(Math.floor(seconds / 60))} min ago`;
            if (seconds < 86_400) return `${String(Math.floor(seconds / 3_600))} h ago`;
            const days = Math.floor(seconds / 86_400);
            return `${String(days)} ${plural(days, `day`, `days`)} ago`;
        },
        botsOnline: `Bots online`,
        allBots: `All bots`,
        buildLead: `Write a program that plays HeXO through the Bot API; it plays everyone here and climbs the ladder.`,
        buildSteps: [`Sign in with Discord`, `Create your bot and copy its token`, `Run the example and watch it play`],
        signedInStep: (name: string) => `Signed in as ${name}`,
        startBuilding: `Start building`,
        readApi: `Read the Bot API`,
        recentFailed: `Recent results did not load`,
    },
    live: {
        title: `Live games`,
        board: (x: string, o: string, toMove: string) => `Board, ${x} vs ${o}, ${toMove} to move`,
        // The list stops at its cap, so a full list says it holds the newest.
        count: (count: number) =>
            count === liveGameListCap ? `The ${String(count)} newest live games` : `${String(count)} live ${plural(count, `game`, `games`)}`,
        failed: `Live games did not load`,
        refreshFailed: `Live games did not refresh; trying again shortly`,
        empty: {
            heading: `No live games right now`,
            body: `Every game shows here while it is played; start one against a bot, or build a bot of your own.`,
            play: `Play a bot`,
            build: `Build a bot`,
        },
    },
    bot: {
        failed: `The bot did not load`,
        missing: (name: ReactNode): ReactNode => rich`No bot named ${name}`,
        browse: `Browse bots`,
        provisionalRating: `Provisional rating`,
        rating: `Rating`,
        online: `Online`,
        offline: `Offline`,
        by: (owner: ReactNode): ReactNode => rich`By ${owner}`,
        playingNow: `Playing now`,
        accepts: `Accepts`,
        acceptsNothing: `Nothing yet`,
        acceptsNothingOwner: (botApi: Slot): ReactNode => rich`Nothing yet; your bot lists the clocks it accepts through the ${botApi(`Bot API`)}.`,
        turnClock: `Turn clock`,
        turnWindow: (min: number, max: number) => `${String(min)} to ${String(max)} s`,
        matchClock: `Match clock`,
        unlimited: `Unlimited`,
        yes: `Yes`,
        no: `No`,
        source: `Source`,
        version: `Version`,
        repository: `Repository`,
        play: (name: ReactNode): ReactNode => rich`Play ${name}`,
        offlineReason: `Offline`,
        closedReason: `Closed for challenges`,
        noClockReason: `Accepts nothing yet`,
        owner: {
            title: `Owner tools`,
            token: `Token`,
            tokenNote: `A new token stops the old one at once; the running bot needs the new one to connect again.`,
            rotate: `Rotate token`,
            rotateArmed: `Rotate; the old token stops now`,
            rotateFailed: `The token did not rotate; the old one still works`,
            delete: `Delete`,
            deleteNote: `Rated games stay on record under "deleted bot"; a bot with no rated games frees its name.`,
            confirmName: (bot: ReactNode): ReactNode => rich`Type ${bot} to confirm`,
            deleteBot: (bot: ReactNode): ReactNode => rich`Delete ${bot}`,
            inGame: (bot: string) => `${bot} is in a game; delete it once the game ends`,
            deleteFailed: (bot: string) => `${bot} was not deleted; try again`,
        },
        token: {
            copy: `Copy`,
            copied: `Copied`,
            once: `This token shows only once; if you lose it, rotate it for a new one.`,
        },
    },
    build: {
        title: `Build a bot`,
        lead: `Get your own bot playing, from sign-in to its first game. An account holds up to ${String(botCapPerUser)} ${plural(botCapPerUser, `bot`, `bots`)}.`,
        signedInAs: (name: ReactNode): ReactNode => rich`Signed in as ${name}`,
        profileNote: (profile: Slot): ReactNode => rich`Your bots are listed on your ${profile(`Profile`)}.`,
        signIn: `Sign in`,
        guestNote: (name: ReactNode): ReactNode => rich`You are playing as ${name}; owning a bot needs a Discord sign-in.`,
        create: `Create your bot`,
        nameLabel: `Bot name`,
        createBot: `Create bot`,
        copyToken: `Copy the token`,
        tokenLater: `The token shows here once, right after you create the bot.`,
        runExample: `Run the example`,
        example: (script: Slot, readme: Slot): ReactNode =>
            rich`A complete bot in Python: ${script(`simple_bot.py`)}, explained in the ${readme(`Bot API readme`)}.`,
        watch: `Watch it play`,
        watchLater: (bots: Slot): ReactNode => rich`Your bot shows as online in ${bots(`Bots`)} once it connects.`,
        botPage: (page: ReactNode): ReactNode => rich`Your bot's page: ${page}`,
        readApi: `Read the Bot API`,
        api: (botApi: Slot): ReactNode => rich`Every endpoint and event, with examples: ${botApi(`Bot API`)}.`,
        nameRule: `${String(nameMinLength)} to ${String(nameMaxLength)} letters, digits, - or _; start with a letter, end with a letter or digit`,
        reserved: `That name is reserved`,
        taken: `That name is taken`,
        atCap: `You already have ${String(botCapPerUser)} ${plural(botCapPerUser, `bot`, `bots`)}; delete one first`,
        signInFirst: `Sign in first (step 1)`,
        failed: `The bot was not created; try again`,
    },
    profile: {
        title: `Profile`,
        signedOut: `Sign in with Discord to see your rating and build a bot.`,
        build: `Build a bot`,
        signOut: `Sign out`,
        signOutFailed: `Sign-out did not go through; you are still signed in`,
        rating: `Rating`,
        discord: ({ username, displayName }: DiscordNames) =>
            `Signed in with Discord as ${displayName === null ? `@${username}` : `${displayName} (@${username})`}`,
        guestNote: `Guest games are unrated and end with the session.`,
        endGuest: `End guest session`,
        endGuestFailed: `The guest session did not end; try again`,
        botsFailed: `Your bots did not load`,
        yourBots: `Your bots`,
        botCount: (count: number): ReactNode => rich`${String(count)} of ${String(botCapPerUser)}`,
        delistedNote: `Delisted bots are hidden here but still count toward your limit of ${String(botCapPerUser)} ${plural(botCapPerUser, `bot`, `bots`)}.`,
    },
    play: {
        title: `Play`,
        opponent: `Opponent`,
        readyCount: (count: number) => (count === 0 ? `No bots ready` : `${String(count)} ${plural(count, `bot`, `bots`)} ready`),
        by: (owner: string) => `By ${owner}`,
        busy: `In ${String(botConcurrentGameCap)} ${plural(botConcurrentGameCap, `game`, `games`)}; try again shortly`,
        reasons: {
            offline: `Offline`,
            closed: `Closed for challenges`,
            nothing: `Accepts nothing yet`,
        },
        others: (count: number, bots: Slot): ReactNode =>
            rich`${String(count)} more ${plural(count, `bot is`, `bots are`)} offline or closed; see ${bots(`Bots`)}.`,
        cardTitle: (name: string) => `Play ${name}`,
        setup: `Game setup`,
        change: `Change`,
        changeOpponent: `Change opponent`,
        closeSheet: `Close the opponent list`,
        clock: `Clock`,
        tiles: {
            t10: { value: `10 s`, kind: `turn clock`, name: `Turn clock, 10 seconds` },
            t20: { value: `20 s`, kind: `turn clock`, name: `Turn clock, 20 seconds` },
            t60: { value: `60 s`, kind: `turn clock`, name: `Turn clock, 60 seconds` },
            // No-break spaces keep each number with its unit on a narrow tile.
            m5: { value: `5\u00a0min +\u00a03\u00a0s`, kind: `match clock`, name: `Match clock, 5 minutes plus 3 seconds` },
            m10: { value: `10\u00a0min +\u00a05\u00a0s`, kind: `match clock`, name: `Match clock, 10 minutes plus 5 seconds` },
            u: { value: `Unlimited`, kind: `no clock`, name: `Unlimited` },
        },
        tileOut: (name: string) => `${name} does not accept this clock`,
        unlimitedNote: `Unlimited games end with no winner after ${String(wallCapHours)} ${plural(wallCapHours, `hour`, `hours`)}.`,
        acceptsLine: (name: string, parts: { turn: readonly [number, number] | null; match: boolean; unlimited: boolean }) => {
            const said = [
                ...(parts.turn === null ? [] : [`turn clocks of ${String(parts.turn[0])} to ${String(parts.turn[1])} s`]),
                ...(parts.match ? [`match clocks`] : []),
                ...(parts.unlimited ? [`unlimited games`] : []),
            ];
            const list = said.length === 1 ? `${said[0] ?? ``} only` : `${said.slice(0, -1).join(`, `)}${said.length > 2 ? `,` : ``} and ${said.at(-1) ?? ``}`;
            return `${name} accepts ${list}.`;
        },
        customClock: `Custom clock`,
        presets: `Presets`,
        turn: `Turn`,
        match: `Match`,
        turnClock: `Turn clock`,
        mainTime: `Main time`,
        increment: `Increment`,
        seconds: (seconds: number) => `${String(seconds)} s`,
        minutes: (minutes: number) => `${String(minutes)} min`,
        plusSeconds: (seconds: number) => `+ ${String(seconds)} s`,
        secondsSpoken: (seconds: number) => `${String(seconds)} seconds`,
        minutesSpoken: (minutes: number) => `${String(minutes)} minutes`,
        plusSecondsSpoken: (seconds: number) => `plus ${String(seconds)} seconds`,
        decrease: (label: string) => `Decrease ${label}`,
        increase: (label: string) => `Increase ${label}`,
        opening: `Opening`,
        openingValue: (count: number) => `${String(count)} ${plural(count, `stone`, `stones`)}`,
        openingStones: `Opening stones, origin included`,
        originOnly: `Only the origin; no random stones.`,
        randomStones: (count: number) => `The origin and ${String(count)} random ${plural(count, `stone`, `stones`)} near it; each game draws its own.`,
        openingExample: (count: number) => `An example opening of ${String(count)} ${plural(count, `stone`, `stones`)}`,
        start: `Start game`,
        rated: `Rated; sides are drawn at random`,
        guestNote: (name: ReactNode): ReactNode => rich`You play as ${name}; guest games are unrated.`,
        signedOutLead: `Play as a guest, unrated, or sign in for a rated game.`,
        playAsGuest: `Play as guest`,
        // A no-break space holds "see Privacy." together, as on every sign-in line.
        notice: (terms: Slot, privacy: Slot): ReactNode =>
            rich`By playing as a guest you accept the ${terms(`Terms`)}, including the minimum age of ${String(minimumAge)}. Your email stays with Discord, and a first sign-in asks for your public name; see\u00a0${privacy(`Privacy`)}.`,
        stale: `You are no longer signed in; sign in again, or play as a guest.`,
        guestStale: `Your guest session ended; play as a guest again, or sign in.`,
        starting: `Starting the game`,
        paused: `Starting games is paused; this page updates when it resumes`,
        unavailable: {
            offline: (name: string) => `${name} is offline; pick another bot`,
            closed: (name: string) => `${name} is closed for challenges right now; pick another bot`,
            nothing: (name: string) => `${name} accepts no clock yet; pick another bot`,
            busy: (name: string) => `${name} is in ${String(botConcurrentGameCap)} ${plural(botConcurrentGameCap, `game`, `games`)} already; try again shortly`,
        },
        yourGame: (opponent: string) => `Your game against ${opponent}`,
        errors: {
            human_busy: () => `You already have ${String(humanConcurrentGameCap)} live ${plural(humanConcurrentGameCap, `game`, `games`)}; finish one first`,
            bot_busy: (name: string) => `${name} is in ${String(botConcurrentGameCap)} ${plural(botConcurrentGameCap, `game`, `games`)} already; try again shortly`,
            clock_not_accepted: (name: string) => `${name} no longer accepts that clock; pick another`,
            not_open: (name: string) => `${name} is closed for challenges right now`,
            delisted: (name: string) => `${name} takes no new games`,
            not_found: (name: string) => `${name} is no longer listed; pick another bot`,
            paused: () => `Starting games is paused; live games continue`,
        },
        cooldown: (seconds: number) => `1 new game ${perMinutes(humanGameCooldownSeconds / 60)}; try again in ${String(seconds)} s`,
        guestLimit: `The guest limit is full; try again in ${inMinutes(guestRetryAfterSeconds / 60)}, or sign in`,
        guestLimited: (seconds: number) => `Too many guest sessions from this network; try again in ${inWait(seconds)}, or sign in`,
        guestFailed: `The guest session did not start; try again`,
        failed: `The game did not start; try again`,
        listFailed: `The bot list did not load`,
        empty: {
            heading: `No bots yet`,
            body: `${siteName} runs no bots of its own; build the first one.`,
            build: `Build a bot`,
        },
        noneReady: {
            heading: `No bots ready right now`,
            body: `A bot plays while its owner runs it and keeps it open for challenges; check back later.`,
            browse: `Browse bots`,
            build: `Build a bot`,
        },
    },
    welcome: {
        title: `Create your account`,
        lead: `Choose the name everyone sees here.`,
        kicker: `Discord account`,
        username: (username: string) => `@${username}`,
        nameLabel: `Public name`,
        free: (name: string) => `${name} is free`,
        nameNote: `Everyone sees this name on the ladder, in your games, and on your bots' pages; it cannot change later.`,
        notice: (terms: Slot, privacy: Slot): ReactNode =>
            rich`By creating your account you accept the ${terms(`Terms`)}, including the minimum age of ${String(minimumAge)}. ${siteName} keeps your Discord user ID and this name, and your Discord names while you are signed in, never your email; see\u00a0${privacy(`Privacy`)}.`,
        create: `Create account`,
        cancel: `Cancel`,
        foot: `If you cancel, nothing is kept. Not your Discord account? Cancel, switch accounts in Discord, and sign in again.`,
        guestNote: `Creating your account ends this guest session and its games.`,
        userNote: (name: string) => `Creating this account signs ${name} out.`,
        createFailed: `The account was not created; try again`,
        expired: `That sign-in expired; sign in again`,
        limit: `That sign-in tried too many names; sign in again`,
        failed: `Your sign-in did not load`,
    },
    credits: {
        title: `Credits`,
        game: `The game`,
        gameAbout: (name: Slot, site: Slot): ReactNode =>
            rich`${name(`HeXO`)} is the game played here: each turn places 2 stones, and 6 in a row wins. People play it at ${site(`hexo.did.science`)}, a site made by WolverinDEV.`,
        gameIndependent: `${siteName} implements the rules independently and is not affiliated with the HeXO project.`,
        themes: `Themes`,
        themesLead: `Ink is ${siteName}'s own. The other themes take their colors, and only their colors, from these projects:`,
        themesSmall: `No code, fonts, images, or logos come from these projects. Where a theme needed a shade its source lacks, it is derived from the source's own colors.`,
        font: `Font`,
        protocol: `Protocol and ratings`,
        inspiration: `Inspiration`,
        inspirationSmall: `No code or design comes from it.`,
        discord: `Discord`,
        licenses: `Licenses`,
        licensesProse: (file: Slot): ReactNode =>
            rich`The open-source code your browser receives, such as React and zod, and the font are listed with their license texts under ${file(`Licenses`)}.`,
        discordProse: `Sign-in uses Discord. The Discord symbol on the sign-in button is shown unaltered under Discord's brand guidelines. Discord is a trademark of Discord Inc.; ${siteName} is not affiliated with Discord.`,
        mit: `MIT License`,
        mitSummary: `The MIT License`,
        mitText: [
            `Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:`,
            `The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.`,
            `THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.`,
        ],
        rows: {
            renderer: { name: `HeXO Renderer`, by: `MineKing`, gives: `HDS, HTTTX, Tyto, and Omok boards and stones`, copyright: `Copyright (c) 2026 MineKing` },
            strix: { name: `Strix`, by: `Tyto (SootyOwl)`, gives: `The Tyto page`, copyright: `Copyright (c) 2026 SootyOwl` },
            playsix: { name: `playsix`, by: `CixMango`, gives: `The Six board, stones, and page`, copyright: `Copyright (c) 2026 CixMango` },
            tailwind: { name: `Tailwind CSS`, by: `Tailwind Labs`, gives: `The HDS page`, copyright: `Copyright (c) Tailwind Labs, Inc.` },
            chakra: {
                name: `Chakra Petch`,
                by: `The Chakra Petch Project Authors`,
                gives: `The ${siteName} wordmark, a subset of the bold weight`,
                terms: `SIL Open Font License 1.1`,
                copyright: `Copyright 2018 The Chakra Petch Project Authors`,
            },
            htttx: {
                name: `htttx bot protocol`,
                by: `hex-tic-tac-toe`,
                gives: (botApi: Slot): ReactNode => rich`The engine session every bot speaks, through the ${botApi(`Bot API`)}`,
                copyright: `Copyright (c) 2026 hex-tic-tac-toe`,
            },
            glicko: { name: `Glicko-2`, by: `Mark Glickman`, gives: `The rating system`, terms: `Published method` },
            lichess: {
                name: `lichess`,
                by: `lichess.org`,
                gives: `How the site works, the rating settings, and the name rule`,
                terms: `Ideas and values only`,
            },
        },
    },
    settings: {
        title: `Settings`,
        close: `Close settings`,
        theme: `Theme`,
        board: `Board`,
        stoneNumbers: `Stone numbers`,
        stoneGlare: `Stone glare`,
        foot: (credits: Slot): ReactNode =>
            rich`Saved in this browser. Every theme but Ink takes its colors from a community project; see ${credits(`Credits`)}.`,
        themes: {
            ink: { name: `Ink`, credit: siteName },
            hds: { name: `HDS`, credit: `hexo.did.science, via MineKing` },
            htttx: { name: `HTTTX`, credit: `HeXO Renderer by MineKing` },
            tyto: { name: `Tyto`, credit: `Tyto's Strix, via MineKing` },
            omok: { name: `Omok`, credit: `HeXO Renderer by MineKing` },
            six: { name: `Six`, credit: `playsix by CixMango` },
        },
    },
    game: {
        failed: `The game did not load`,
        missingHeading: `No such game`,
        missingSentence: `That game does not exist; guest games are gone once their session ends.`,
        panelToggle: `Game panel`,
        exit: `Home`,
        you: `you`,
        vs: (x: string, o: string) => `${x} vs ${o}`,
        unrated: `unrated`,
        playing: (side: ReactNode): ReactNode => rich`Playing ${side}`,
        watching: `watching`,
        manyWatching: `Many watching; the board catches up shortly`,
        connectionLost: `Connection lost; reconnecting`,
        home: `Home`,
        thinking: (name: ReactNode): ReactNode => rich`${name} is thinking`,
        yourTurn: `Your turn`,
        twoStones: `2 stones`,
        oneStoneLeft: `1 stone left`,
    },
    replay: {
        label: `Turn`,
        turn: (turn: number, last: number) => `Turn ${String(turn)} of ${String(last)}`,
        firstStone: (turn: number, last: number) => `Turn ${String(turn)} of ${String(last)}, first stone`,
        live: (words: string) => `${words}, live`,
        latest: (last: number) => `Turn ${String(last)}, live`,
        opening: (stones: number) => `Opening, ${String(stones)} ${plural(stones, `stone`, `stones`)}`,
        origin: `Origin only`,
        toOpening: `Go to the opening`,
        back: `Go back a turn`,
        on: `Go forward a turn`,
        toEnd: `Go to the end`,
        toLatest: `Go to the latest turn`,
        liveSwitch: `Live`,
    },
    drawer: {
        panel: `Game panel`,
        open: `Open the game panel`,
        close: `Close the game panel`,
        moves: `Moves`,
        game: `Game`,
        pin: `Pin`,
        unpin: `Unpin`,
        clock: `Clock`,
        opening: `Opening`,
        originOnly: `Origin only`,
        clockValue: (words: string) => `${words.charAt(0).toUpperCase()}${words.slice(1)}`,
        openingStones: (count: number) => `${String(count)} ${plural(count, `stone`, `stones`)}, origin included`,
        rated: `Rated`,
        ratedYes: `Yes`,
        ratedNoGuest: `No, a guest is playing`,
        yourSide: `Your side`,
        result: `Result`,
        keys: (key: Slot): ReactNode =>
            rich`${key(`Arrows`)}, ${key(`q`)} and ${key(`e`)} move between cells; ${key(`Enter`)} marks a stone and a second mark plays the turn; ${key(`Esc`)} clears the mark; ${key(`m`)} opens this panel.`,
        watchKeys: (key: Slot): ReactNode => rich`With the board focused, ${key(`arrows`)} scroll it; ${key(`m`)} opens this panel.`,
        leave: `Home`,
        leaveNote: `Leaving does not resign; your clock keeps running.`,
        resign: `Resign`,
        confirmResign: `Resign and lose`,
        resignFailed: `The resignation was not sent; try again`,
        openingLabel: `op 0`,
        openingSpoken: `opening, turn 0`,
        openingRangeLabel: (last: number) => `op 0-${String(last)}`,
        openingRangeSpoken: (last: number) => `opening, turns 0 to ${String(last)}`,
        spokenLabel: (spoken: string) => `${spoken},`,
        board: (state: string) => `Board, ${state}`,
        boardYourTurn: `your turn: 2 stones`,
        boardStones: (count: number) => `Game board, ${String(count)} ${plural(count, `stone`, `stones`)} placed`,
        boardFinished: `game finished`,
        boardToMove: (name: string) => `${name} to move`,
        boardWaiting: (name: string) => `waiting for ${name}`,
        boardWatching: (match: string, state: string) => `watching ${match}, ${state}`,
        turnFailed: `Your turn was not sent; try again`,
        gameOver: `The game is over`,
        cellTaken: `That cell is taken`,
        firstAtOrigin: `The first stone belongs at the origin`,
        tooFar: `Too far; play within ${String(placementRadius)} cells of a stone`,
    },
    states: {
        loading: `Loading`,
        tryAgain: `Try again`,
        tooMany: (seconds: number) => `Too many tries; try again in ${inWait(seconds)}`,
        notFoundHeading: `Not found`,
        notFoundSentence: `That page does not exist.`,
        notFoundHome: `Home`,
        routeFailed: `This page did not load`,
        routeFailedSentence: `Part of it did not download; reload to try again.`,
        routeCrashedSentence: `An error stopped it; reload to try again.`,
        reload: `Reload`,
        routeFailedHome: `Home`,
    },
    meta: {
        game: `Game`,
    },
};

/** The catalog's shape, which a catalog in any other language must match. */
export type Catalog = typeof en;
