import {
    botCapPerUser,
    botConcurrentGameCap,
    guestRetryAfterSeconds,
    humanConcurrentGameCap,
    humanGameCooldownSeconds,
    liveGameListCap,
    minimumAge,
    nameMaxLength,
    nameMinLength,
    pairDailyCap,
    placementRadius,
    plural,
    siteName,
    unlimitedWallCapMs,
    type DiscordNames,
    type LegalPage,
    type SignInFailure,
} from '@hexo-arena/contract';
import type { ReactNode } from 'react';
import { rich, type Slot } from './rich';

const wallCapHours = unlimitedWallCapMs / 3_600_000;

// A wait in whole minutes, as a rate and as a delay: "a minute" for one.
const perMinutes = (minutes: number) => (minutes === 1 ? `a minute` : `every ${String(minutes)} minutes`);
const inMinutes = (minutes: number) => (minutes === 1 ? `a minute` : `${String(minutes)} minutes`);
// A place in English: 1st, 2nd, 3rd, 4th, and 11th to 13th.
function ordinal(place: number): string {
    const tens = place % 100;
    const ones = place % 10;
    const suffix = tens >= 11 && tens <= 13 ? `th` : ones === 1 ? `st` : ones === 2 ? `nd` : ones === 3 ? `rd` : `th`;
    return `${String(place)}${suffix}`;
}
// A count in the catalog's language, its thousands grouped: 1,234.
const countFormat = new Intl.NumberFormat(`en-US`);
const counted = (count: number) => countFormat.format(count);
// A wait the server named, in seconds under a minute and whole minutes, rounded up, past it.
const inWait = (seconds: number) => (seconds < 60 ? `${String(seconds)} s` : inMinutes(Math.ceil(seconds / 60)));

/** A link to each legal page the deployment has; a page it lacks is null, and its words go with it. */
export type LegalSlots = Readonly<Record<LegalPage, Slot | null>>;

// A no-break space holds "see Privacy." together, so a line never ends on
// a word alone at any width or text size.
const seePrivacy = (privacy: Slot | null): ReactNode => (privacy === null ? `` : rich`; see\u00a0${privacy(`Privacy`)}`);

/**
 * The words the web app shows, in English, grouped by screen and area.
 * Text the server also renders, from the site's name and tagline to page
 * titles, results, and clock words, lives in the contract instead.
 * Text with values in it is a function of those values, and text with
 * elements in it takes a {@link Slot} per element.
 * Limits and counts come from the contract's constants and its plural.
 */
export const en = {
    shell: {
        skipToContent: `Skip to content`,
        mainNav: `Main`,
        nav: {
            home: `Home`,
            play: `Play`,
            games: `Games`,
            ladder: `Ladder`,
            bots: `Bots`,
            build: `Build a bot`,
        },
        paused: `Starting games is paused; live games continue`,
        links: {
            tournaments: `Tournaments`,
            build: `Build a bot`,
            credits: `Credits`,
            botApi: `Bot API`,
            source: `Source`,
            imprint: `Impressum / Legal notice`,
            privacy: `Privacy`,
            terms: `Terms`,
            licenses: `Licenses`,
        },
        opensInNewTab: (label: string) => `${label}, opens in a new tab`,
        signIn: (provider: Slot): ReactNode => rich`Sign in${provider(` with Discord`)}`,
        trustLine: (privacy: Slot | null): ReactNode => rich`Your email stays with Discord, and a first sign-in asks for your public name${seePrivacy(privacy)}.`,
        guestTrustLine: (privacy: Slot | null): ReactNode => rich`Signing in ends this guest session and its games. Your email stays with Discord${seePrivacy(privacy)}.`,
        signInFailed: {
            unconfigured: () => `Sign-in is not set up on this server`,
            cancelled: () => `You cancelled the sign-in at Discord; nothing was kept`,
            expired: () => `That sign-in expired; sign in again`,
            rejected: () => `Discord did not confirm the sign-in; try again`,
            banned: ({ imprint, privacy }: LegalSlots): ReactNode =>
                imprint !== null
                    ? rich`This Discord account is banned from ${siteName}; the operator's contact is in the ${imprint(`Legal notice`)}`
                    : privacy !== null
                      ? rich`This Discord account is banned from ${siteName}; the operator's contact is in the ${privacy(`Privacy policy`)}`
                      : `This Discord account is banned from ${siteName}`,
            busy: () => `Sign-in is busy right now; try again in a minute`,
        } satisfies Record<SignInFailure, (legal: LegalSlots) => ReactNode>,
        identity: {
            guestName: (name: string) => `${name}, unrated`,
            discord: ({ username, displayName }: DiscordNames) =>
                displayName === null ? `Discord: @${username}` : `Discord: ${displayName} (@${username})`,
            unrated: `unrated`,
            close: `Close menu`,
            rating: (spoken: Slot, value: ReactNode): ReactNode => rich`${spoken(`, rating `)}${value}`,
            profile: `Profile`,
            build: `Build a bot`,
            signOut: `Sign out`,
            signOutFailed: `Sign-out did not go through; you are still signed in`,
            endGuest: `End guest session`,
            endGuestNote: `Your guest games end with it.`,
            endGuestFailed: `The guest session did not end; try again`,
        },
    },
    player: {
        botBadge: `BOT`,
        online: `Online`,
        offline: `Offline`,
        open: `open`,
        closed: `closed`,
        provisional: `Provisional until the rating settles`,
        acceptsTurn: (min: number, max: number) => `turn ${String(min)} to ${String(max)} s`,
        acceptsMatch: `match`,
        acceptsUnlimited: `unlimited`,
        acceptsList: (parts: readonly string[]) => parts.join(`, `),
    },
    ladder: {
        title: `Ladder`,
        kinds: {
            all: `All`,
            bots: `Bots`,
            humans: `Humans`,
        },
        kindFilter: `Show`,
        failed: `The ladder did not load`,
        pulse: (
            ranked: number,
            kind: `all` | `bots` | `humans`,
            roster: { online: number; open: number } | null,
            strong: Slot,
            dot: ReactNode,
        ): ReactNode => {
            const nouns = { all: [`player`, `players`], bots: [`bot`, `bots`], humans: [`human`, `humans`] } as const;
            const count = rich`${strong(String(ranked))} ranked ${plural(ranked, nouns[kind][0], nouns[kind][1])}`;
            if (roster === null) return count;
            if (roster.online === 0) return rich`${count}; no bots online`;
            const open = roster.open === 0 ? `none` : strong(String(roster.open));
            return rich`${count}; ${dot}${strong(String(roster.online))} ${plural(roster.online, `bot`, `bots`)} online, ${open} open for challenges`;
        },
        top: `Top of the ladder`,
        human: `Human`,
        by: (owner: ReactNode): ReactNode => rich`By ${owner}`,
        full: `Full ladder`,
        rank: `Rank`,
        player: `Player`,
        rating: `Rating`,
        games: `Games`,
        lastPlayed: `Last played`,
        byOwner: (owner: ReactNode): ReactNode => rich`by ${owner}`,
        you: `you`,
        lead: `One rating pool for bots and humans; a player joins once their rating is no longer provisional.`,
        played: `Played`,
        playedWithin: { '30d': `in the last 30 days`, all: `all time` },
        find: `Find a name`,
        findNone: (name: string) => `No player on this ladder matches ${name}`,
        findCount: (count: number, name: string) =>
            count === 0 ? `No player on this ladder matches ${name}` : `${String(count)} ${plural(count, `player matches`, `players match`)} ${name}`,
        yourPlace: (rank: number, rating: number) => `You are ${ordinal(rank)} with ${String(rating)}`,
        showMine: `Show my row`,
        settling: `Your rating is still settling; you join the ladder once it is no longer provisional.`,
        podiumLabel: (top: readonly { name: string; rating: number }[]) =>
            `Podium: ${top.map((entry, index) => `${[`first`, `second`, `third`][index] ?? ``} ${entry.name}, ${String(entry.rating)}`).join(`; `)}`,
        plateMeta: (owner: ReactNode | null, games: number): ReactNode => {
            const played = `${String(games)} ${plural(games, `game`, `games`)}`;
            return owner === null ? played : rich`by ${owner}, ${played}`;
        },
        play: `Play`,
        playBot: (name: string) => `Play ${name}`,
        empty: {
            heading: `No ranked players yet`,
            body: `A player joins the ladder once their rating is no longer provisional. ${siteName} runs no bots of its own; the ladder is whatever you bring.`,
            build: `Build a bot`,
            browse: `Browse bots`,
        },
        quiet: {
            heading: `No ranked player played in the last 30 days`,
            body: `Players who sat out the month stay on the ladder for all time.`,
            all: `Show all time`,
        },
        live: {
            title: `Live games`,
            all: `All live games`,
            failed: `Live games did not load; trying again shortly`,
            none: `No live games right now.`,
            watch: `Watch `,
            vs: `vs`,
            unrated: `unrated`,
            toMove: (name: ReactNode): ReactNode => rich`${name} to move`,
        },
    },
    bots: {
        title: `Bots`,
        build: `Build a bot`,
        onlineOnly: `Online only`,
        failed: `The bot list did not load`,
        bot: `Bot`,
        owner: `Owner`,
        challenges: `Challenges`,
        rating: `Rating`,
        accepts: `Accepts`,
        version: `Version`,
        playColumn: `Play`,
        noneOnline: `No bots online right now; clear Online only to see every bot.`,
        online: `Online`,
        offline: `Offline`,
        openKey: `open: takes challenges now`,
        provisionalKey: `?: provisional rating`,
        play: `Play`,
        playBot: (name: string) => `Play ${name}`,
        busy: `In ${String(botConcurrentGameCap)} ${plural(botConcurrentGameCap, `game`, `games`)}`,
        empty: {
            heading: `No bots yet`,
            body: `${siteName} runs no bots of its own; build the first one.`,
            build: `Build a bot`,
        },
    },
    home: {
        title: `Play HeXO`,
        rules: `Six in a row wins; each turn places two stones.`,
        playBot: `Play a bot`,
        noneOnline: `No bots online right now`,
        noBots: `${siteName} runs no bots of its own; the ladder is whatever you bring.`,
        build: `Build a bot`,
        lastGame: (game: Slot, x: string, o: string, result: string): ReactNode => rich`Last game: ${game(`${x} vs ${o}`)}; ${result}`,
        yourGames: `Your games`,
        against: (name: string) => `Against ${name}`,
        yourTurn: `Your turn`,
        toMove: (name: string) => `${name} to move`,
        featured: `Featured game`,
        watch: (x: string, o: string) => `Watch ${x} vs ${o}`,
        ended: `Just finished`,
        last: `Last game`,
        replay: (x: string, o: string) => `Replay ${x} vs ${o}`,
        liveNow: `Live now`,
        allLive: `All live games`,
        ladder: `Ladder`,
        fullLadder: `Full ladder`,
        allTime: `All time; no ranked player played in the last 30 days.`,
        settling: `Settling ratings`,
        settlingNote: `No ranked players yet; a player joins the ladder once their rating is no longer provisional.`,
        recent: `Recent results`,
        tournament: `Tournament`,
        allTournaments: `All tournaments`,
        tournamentRunning: (bots: number, clock: string) => `${String(bots)} ${plural(bots, `bot`, `bots`)}; ${clock}`,
        tournamentLive: `live`,
        tournamentStarts: (entered: number, max: number) => `${String(entered)} of ${String(max)} bots entered`,
        tournamentIn: (wait: string) => `in ${wait}`,
        allGames: `All games`,
        botsOnline: `Bots online`,
        allBots: `All bots`,
        buildLead: `Write a program that plays HeXO through the Bot API; it plays everyone here and climbs the ladder.`,
        buildSteps: [`Sign in with Discord`, `Create your bot and copy its token`, `Run the example and watch it play`],
        signedInStep: (name: string) => `Signed in as ${name}`,
        startBuilding: `Start building`,
        readApi: `Read the Bot API`,
        recentFailed: `Recent results did not load`,
    },
    live: {
        title: `Live games`,
        board: (x: string, o: string, toMove: string) => `Board, ${x} vs ${o}, ${toMove} to move`,
        // The list stops at its cap, so a full list says it holds the newest.
        count: (count: number) =>
            count === liveGameListCap ? `The ${String(count)} newest live games` : `${String(count)} live ${plural(count, `game`, `games`)}`,
        failed: `Live games did not load`,
        refreshFailed: `Live games did not refresh; trying again shortly`,
        empty: {
            heading: `No live games right now`,
            body: `Every game shows here while it is played; start one against a bot, or build a bot of your own.`,
            play: `Play a bot`,
            build: `Build a bot`,
        },
    },
    games: {
        title: `Games`,
        views: `Games`,
        finished: `Finished`,
        live: `Live`,
        note: `Newest first; guest games are not kept, so they never show here.`,
        search: `Filter games`,
        filters: (count: number) => (count === 0 ? `Filters` : `Filters (${String(count)})`),
        needPlayer: `Against, Side, Won, and Lost wait for a name in Player.`,
        openingNote: `Opening counts the stones on the board before the first turn, the origin and random ones near it.`,
        player: `Player`,
        vs: `Against`,
        result: `Result`,
        side: `Side`,
        reason: `Ending`,
        clock: `Clock`,
        kind: `Who played`,
        opening: `Opening`,
        before: `Before`,
        any: `Any`,
        results: { won: `Won`, lost: `Lost`, none: `No winner` },
        clocks: { turn: `Turn clock`, match: `Match clock`, unlimited: `Unlimited` },
        kinds: { 'bot-bot': `Bot vs bot`, 'human-bot': `Human vs bot` },
        openingValue: (stones: number) => (stones === 1 ? `Origin only` : `${String(stones)} stones`),
        chips: {
            vs: (name: string) => `against ${name}`,
            results: { won: `won`, lost: `lost`, none: `no winner` },
            side: (side: string) => `as ${side}`,
            clocks: { turn: `turn clock`, match: `match clock`, unlimited: `unlimited` },
            kinds: { 'bot-bot': `bot vs bot`, 'human-bot': `human vs bot` },
            opening: (stones: number) => (stones === 1 ? `origin only` : `${String(stones)}-stone opening`),
            before: (date: string) => `before ${date}`,
        },
        chipsLabel: `Active filters`,
        remove: (chip: string) => `Remove ${chip}`,
        clear: `Clear filters`,
        gamesOf: (name: string) => `All games of ${name}`,
        show: `Show games`,
        closeSheet: `Close filters`,
        columns: { players: `Players`, result: `Result`, clock: `Clock`, opening: `Opening`, length: `Length`, finished: `Finished` },
        versus: `vs`,
        voided: `voided`,
        turns: (count: number) => `${String(count)} ${plural(count, `turn`, `turns`)}`,
        count: (count: number) => `${counted(count)} ${plural(count, `game`, `games`)}`,
        pageOf: (page: number, pages: number, count: number) => `Page ${String(page)} of ${String(pages)}; ${counted(count)} ${plural(count, `game`, `games`)}`,
        pageLink: (page: number) => `Page ${String(page)}`,
        listed: (page: number) => `Games, page ${String(page)}`,
        paging: `Pages`,
        previous: `Previous`,
        next: `Next`,
        cap: (shown: number, count: number) => `Showing the newest ${String(shown)} of ${counted(count)}; pick an earlier date in Filters for older games.`,
        pickBefore: `Pick a date`,
        failed: `The games did not load`,
        dayOne: {
            heading: `No finished games yet`,
            body: `A game lands here the moment it ends.`,
            watch: `Watch a live game`,
            build: `Build a bot`,
        },
        noMatch: {
            heading: `No games match these filters`,
            body: (filters: string) => `No finished game matches ${filters}.`,
        },
        unknown: (name: ReactNode): ReactNode => rich`No player named ${name}`,
        unknownBody: `A name must match in full; capitals do not matter.`,
        against: (player: ReactNode, vs: ReactNode): ReactNode => rich`${player} against ${vs}`,
        won: (name: string) => `${name} won`,
        noWinner: `No winner`,
        split: (player: string, games: number, x: { games: number; won: number; lost: number }, o: { games: number; won: number; lost: number }) => {
            const total = `${String(games)} ${plural(games, `game`, `games`)}`;
            const line = (side: { won: number; lost: number }) => `won ${String(side.won)} and lost ${String(side.lost)}`;
            if (x.games === 0) return `${total}; ${player} ${line(o)}, all as o.`;
            if (o.games === 0) return `${total}; ${player} ${line(x)}, all as x.`;
            return `${total}; ${player} ${line(x)} as x, and ${line(o)} as o.`;
        },
        voidedLeftOut: (count: number) => `${String(count)} voided ${plural(count, `game is`, `games are`)} left out`,
        recent: `Recent games`,
        yours: `Your games`,
        none: `No finished games yet.`,
        all: (count: number) => (count === 1 ? `The 1 game` : `All ${String(count)} games`),
        meetings: (x: ReactNode, o: ReactNode, won: number, lost: number, games: (words: string) => ReactNode, count: number): ReactNode =>
            rich`${x} won ${String(won)} and ${o} ${String(lost)} of their ${games(`${String(count)} ${plural(count, `game`, `games`)}`)}`,
    },
    bot: {
        failed: `The bot did not load`,
        missing: (name: ReactNode): ReactNode => rich`No bot named ${name}`,
        browse: `Browse bots`,
        provisionalRating: `Provisional rating`,
        rating: `Rating`,
        online: `Online`,
        offline: `Offline`,
        by: (owner: ReactNode): ReactNode => rich`By ${owner}`,
        playingNow: `Playing now`,
        accepts: `Accepts`,
        acceptsNothing: `Nothing yet`,
        acceptsNothingOwner: (botApi: Slot): ReactNode => rich`Nothing yet; your bot lists the clocks it accepts through the ${botApi(`Bot API`)}.`,
        turnClock: `Turn clock`,
        turnWindow: (min: number, max: number) => `${String(min)} to ${String(max)} s`,
        matchClock: `Match clock`,
        unlimited: `Unlimited`,
        yes: `Yes`,
        no: `No`,
        source: `Source`,
        version: `Version`,
        repository: `Repository`,
        play: (name: ReactNode): ReactNode => rich`Play ${name}`,
        offlineReason: `Offline`,
        closedReason: `Closed for challenges`,
        noClockReason: `Accepts nothing yet`,
        owner: {
            title: `Owner tools`,
            token: `Token`,
            tokenNote: `A new token stops the old one at once; the running bot needs the new one to connect again.`,
            rotate: `Rotate token`,
            rotateArmed: `Rotate; the old token stops now`,
            rotateFailed: `The token did not rotate; the old one still works`,
            delete: `Delete`,
            deleteNote: `Rated games stay on record under "deleted bot"; a bot with no rated games frees its name.`,
            confirmName: (bot: ReactNode): ReactNode => rich`Type ${bot} to confirm`,
            deleteBot: (bot: ReactNode): ReactNode => rich`Delete ${bot}`,
            inGame: (bot: string) => `${bot} is in a game; delete it once the game ends`,
            deleteFailed: (bot: string) => `${bot} was not deleted; try again`,
        },
        token: {
            copy: `Copy`,
            copied: `Copied`,
            once: `This token shows only once; if you lose it, rotate it for a new one.`,
        },
    },
    build: {
        title: `Build a bot`,
        lead: `Get your own bot playing, from sign-in to its first game. An account holds up to ${String(botCapPerUser)} ${plural(botCapPerUser, `bot`, `bots`)}.`,
        signedInAs: (name: ReactNode): ReactNode => rich`Signed in as ${name}`,
        profileNote: (profile: Slot): ReactNode => rich`Your bots are listed on your ${profile(`Profile`)}.`,
        signIn: `Sign in`,
        guestNote: (name: ReactNode): ReactNode => rich`You are playing as ${name}; owning a bot needs a Discord sign-in.`,
        create: `Create your bot`,
        nameLabel: `Bot name`,
        createBot: `Create bot`,
        copyToken: `Copy the token`,
        tokenLater: `The token shows here once, right after you create the bot.`,
        runExample: `Run the example`,
        example: (script: Slot, readme: Slot): ReactNode =>
            rich`A complete bot in Python: ${script(`simple_bot.py`)}, explained in the ${readme(`Bot API readme`)}.`,
        watch: `Watch it play`,
        watchLater: (bots: Slot): ReactNode => rich`Your bot shows as online in ${bots(`Bots`)} once it connects.`,
        botPage: (page: ReactNode): ReactNode => rich`Your bot's page: ${page}`,
        readApi: `Read the Bot API`,
        api: (botApi: Slot): ReactNode => rich`Every endpoint and event, with examples: ${botApi(`Bot API`)}.`,
        nameRule: `${String(nameMinLength)} to ${String(nameMaxLength)} letters, digits, - or _; start with a letter, end with a letter or digit`,
        reserved: `That name is reserved`,
        taken: `That name is taken`,
        atCap: `You already have ${String(botCapPerUser)} ${plural(botCapPerUser, `bot`, `bots`)}; delete one first`,
        signInFirst: `Sign in first (step 1)`,
        failed: `The bot was not created; try again`,
    },
    profile: {
        title: `Profile`,
        signedOut: `Sign in with Discord to see your rating and build a bot.`,
        build: `Build a bot`,
        signOut: `Sign out`,
        signOutFailed: `Sign-out did not go through; you are still signed in`,
        rating: `Rating`,
        discord: ({ username, displayName }: DiscordNames) =>
            `Signed in with Discord as ${displayName === null ? `@${username}` : `${displayName} (@${username})`}`,
        guestNote: `Guest games are unrated and end with the session.`,
        endGuest: `End guest session`,
        endGuestFailed: `The guest session did not end; try again`,
        botsFailed: `Your bots did not load`,
        yourBots: `Your bots`,
        botCount: (count: number): ReactNode => rich`${String(count)} of ${String(botCapPerUser)}`,
        delistedNote: `Delisted bots are hidden here but still count toward your limit of ${String(botCapPerUser)} ${plural(botCapPerUser, `bot`, `bots`)}.`,
    },
    play: {
        title: `Play`,
        opponent: `Opponent`,
        readyCount: (count: number) => (count === 0 ? `No bots ready` : `${String(count)} ${plural(count, `bot`, `bots`)} ready`),
        by: (owner: string) => `By ${owner}`,
        busy: `In ${String(botConcurrentGameCap)} ${plural(botConcurrentGameCap, `game`, `games`)}; try again shortly`,
        reasons: {
            offline: `Offline`,
            closed: `Closed for challenges`,
            nothing: `Accepts nothing yet`,
        },
        inTournament: `In a tournament until it ends`,
        others: (count: number, bots: Slot): ReactNode =>
            rich`${String(count)} more ${plural(count, `bot is`, `bots are`)} offline or closed; see ${bots(`Bots`)}.`,
        cardTitle: (name: string) => `Play ${name}`,
        setup: `Game setup`,
        change: `Change`,
        changeOpponent: `Change opponent`,
        closeSheet: `Close the opponent list`,
        clock: `Clock`,
        tiles: {
            t10: { value: `10 s`, kind: `turn clock`, name: `Turn clock, 10 seconds` },
            t20: { value: `20 s`, kind: `turn clock`, name: `Turn clock, 20 seconds` },
            t60: { value: `60 s`, kind: `turn clock`, name: `Turn clock, 60 seconds` },
            // No-break spaces keep each number with its unit on a narrow tile.
            m5: { value: `5\u00a0min +\u00a03\u00a0s`, kind: `match clock`, name: `Match clock, 5 minutes plus 3 seconds` },
            m10: { value: `10\u00a0min +\u00a05\u00a0s`, kind: `match clock`, name: `Match clock, 10 minutes plus 5 seconds` },
            u: { value: `Unlimited`, kind: `no clock`, name: `Unlimited` },
        },
        tileOut: (name: string) => `${name} does not accept this clock`,
        unlimitedNote: `Unlimited games end with no winner after ${String(wallCapHours)} ${plural(wallCapHours, `hour`, `hours`)}.`,
        acceptsLine: (name: string, parts: { turn: readonly [number, number] | null; match: boolean; unlimited: boolean }) => {
            const said = [
                ...(parts.turn === null ? [] : [`turn clocks of ${String(parts.turn[0])} to ${String(parts.turn[1])} s`]),
                ...(parts.match ? [`match clocks`] : []),
                ...(parts.unlimited ? [`unlimited games`] : []),
            ];
            const list = said.length === 1 ? `${said[0] ?? ``} only` : `${said.slice(0, -1).join(`, `)}${said.length > 2 ? `,` : ``} and ${said.at(-1) ?? ``}`;
            return `${name} accepts ${list}.`;
        },
        customClock: `Custom clock`,
        presets: `Presets`,
        turn: `Turn`,
        match: `Match`,
        turnClock: `Turn clock`,
        mainTime: `Main time`,
        increment: `Increment`,
        seconds: (seconds: number) => `${String(seconds)} s`,
        minutes: (minutes: number) => `${String(minutes)} min`,
        plusSeconds: (seconds: number) => `+ ${String(seconds)} s`,
        secondsSpoken: (seconds: number) => `${String(seconds)} seconds`,
        minutesSpoken: (minutes: number) => `${String(minutes)} minutes`,
        plusSecondsSpoken: (seconds: number) => `plus ${String(seconds)} seconds`,
        decrease: (label: string) => `Decrease ${label}`,
        increase: (label: string) => `Increase ${label}`,
        opening: `Opening`,
        openingValue: (count: number) => `${String(count)} ${plural(count, `stone`, `stones`)}`,
        openingStones: `Opening stones, origin included`,
        openingNote: (stones: number) =>
            `Before the first turn the server places the origin stone and a few random stones near it, so games start differently; ${String(stones)} means the origin ${stones === 1 ? `alone` : `and ${String(stones - 1)} more`}.`,
        openingExample: (count: number) => `An example opening of ${String(count)} ${plural(count, `stone`, `stones`)}`,
        start: `Start game`,
        expected: (bot: string, score: string) => `Your expected score against ${bot}: ${score}`,
        rated: `Rated; sides are drawn at random`,
        guestNote: (name: ReactNode): ReactNode => rich`You play as ${name}; guest games are unrated.`,
        signedOutLead: `Play as a guest, unrated, or sign in for a rated game.`,
        playAsGuest: `Play as guest`,
        notice: ({ terms, privacy }: LegalSlots): ReactNode =>
            rich`${terms === null ? `` : rich`By playing as a guest you accept the ${terms(`Terms`)}, including the minimum age of ${String(minimumAge)}. `}Your email stays with Discord, and a first sign-in asks for your public name${seePrivacy(privacy)}.`,
        stale: `You are no longer signed in; sign in again, or play as a guest.`,
        guestStale: `Your guest session ended; play as a guest again, or sign in.`,
        starting: `Starting the game`,
        paused: `Starting games is paused; this page updates when it resumes`,
        unavailable: {
            tournament: (name: string, tournament: ReactNode | null): ReactNode =>
                tournament === null ? `${name} is in a tournament until it ends; pick another bot` : rich`${name} is in ${tournament} until it ends; pick another bot`,
            offline: (name: string) => `${name} is offline; pick another bot`,
            closed: (name: string) => `${name} is closed for challenges right now; pick another bot`,
            nothing: (name: string) => `${name} accepts no clock yet; pick another bot`,
            busy: (name: string) => `${name} is in ${String(botConcurrentGameCap)} ${plural(botConcurrentGameCap, `game`, `games`)} already; try again shortly`,
            own: (name: string) => `${name} is your own bot; pick another bot`,
        },
        yourGame: (opponent: string) => `Your game against ${opponent}`,
        errors: {
            human_busy: () => `You already have ${String(humanConcurrentGameCap)} live ${plural(humanConcurrentGameCap, `game`, `games`)}; finish one first`,
            bot_busy: (name: string) => `${name} is in ${String(botConcurrentGameCap)} ${plural(botConcurrentGameCap, `game`, `games`)} already; try again shortly`,
            clock_not_accepted: (name: string) => `${name} no longer accepts that clock; pick another`,
            not_open: (name: string) => `${name} is closed for challenges right now`,
            delisted: (name: string) => `${name} takes no new games`,
            not_found: (name: string) => `${name} is no longer listed; pick another bot`,
            own_bot: (name: string) => `${name} is your own bot; pick another bot`,
            daily_pair_cap: (name: string) =>
                `You have played ${name} ${String(pairDailyCap)} times today, the most one day allows; pick another bot, or play it again after 00:00 UTC`,
            paused: () => `Starting games is paused; live games continue`,
        },
        cooldown: (seconds: number) => `1 new game ${perMinutes(humanGameCooldownSeconds / 60)}; try again in ${String(seconds)} s`,
        guestLimit: `The guest limit is full; try again in ${inMinutes(guestRetryAfterSeconds / 60)}, or sign in`,
        guestLimited: (seconds: number) => `Too many guest sessions from this network; try again in ${inWait(seconds)}, or sign in`,
        guestFailed: `The guest session did not start; try again`,
        failed: `The game did not start; try again`,
        listFailed: `The bot list did not load`,
        empty: {
            heading: `No bots yet`,
            body: `${siteName} runs no bots of its own; build the first one.`,
            build: `Build a bot`,
        },
        noneReady: {
            heading: `No bots ready right now`,
            body: `A bot plays while its owner runs it and keeps it open for challenges; check back later.`,
            browse: `Browse bots`,
            build: `Build a bot`,
        },
    },
    welcome: {
        title: `Create your account`,
        lead: `Choose the name everyone sees here.`,
        kicker: `Discord account`,
        username: (username: string) => `@${username}`,
        nameLabel: `Public name`,
        free: (name: string) => `${name} is free`,
        nameNote: `Everyone sees this name on the ladder, in your games, and on your bots' pages; it cannot change later.`,
        notice: ({ terms, privacy }: LegalSlots): ReactNode =>
            rich`${terms === null ? `` : rich`By creating your account you accept the ${terms(`Terms`)}, including the minimum age of ${String(minimumAge)}. `}${siteName} keeps your Discord user ID and this name, and your Discord names while you are signed in, never your email${seePrivacy(privacy)}.`,
        create: `Create account`,
        cancel: `Cancel`,
        foot: `If you cancel, nothing is kept. Not your Discord account? Cancel, switch accounts in Discord, and sign in again.`,
        guestNote: `Creating your account ends this guest session and its games.`,
        userNote: (name: string) => `Creating this account signs ${name} out.`,
        createFailed: `The account was not created; try again`,
        expired: `That sign-in expired; sign in again`,
        limit: `That sign-in tried too many names; sign in again`,
        failed: `Your sign-in did not load`,
    },
    credits: {
        title: `Credits`,
        game: `The game`,
        gameAbout: (name: Slot): ReactNode => rich`${name(`HeXO`)} is the game played here: each turn places 2 stones, and 6 in a row wins.`,
        community: `Community`,
        marks: `Discord, GitHub, and YouTube are trademarks of Discord Inc., GitHub Inc., and Google LLC.`,
        themes: `Themes`,
        themesLead: `Ink is ${siteName}'s own. The other themes take their colors from these projects:`,
        font: `Font`,
        protocol: `Protocol and ratings`,
        inspiration: `Inspiration`,
        licenses: `Licenses`,
        licensesProse: (file: Slot): ReactNode =>
            rich`The open-source code your browser receives, such as React and zod, the font, and GitHub's mark are listed with their license texts under ${file(`Licenses`)}.`,
        platforms: { youtube: `YouTube`, discord: `Discord` },
        mit: `MIT License`,
        mitSummary: `The MIT License`,
        mitText: [
            `Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:`,
            `The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.`,
            `THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.`,
        ],
        rows: {
            webgoatguy: {
                name: `webgoatguy`,
                gives: (video: Slot): ReactNode => rich`Came up with HeXO in the video ${video(`can tic-tac-toe, with hexagons?`)}`,
            },
            hexoSite: { name: `hexo.did.science`, by: `WolverinDEV`, gives: `Where people play HeXO online` },
            hexoDiscord: { name: `HeXO - Official`, gives: `The game's official community` },
            botDevDiscord: { name: `HexO Bot Dev`, gives: `Where people build HeXO bots` },
            renderer: { name: `HeXO Renderer`, by: `MineKing`, gives: `HDS, HTTTX, Tyto, and Omok boards and stones`, copyright: `Copyright (c) 2026 MineKing` },
            strix: { name: `Strix`, by: `Tyto (SootyOwl)`, gives: `The Tyto page`, copyright: `Copyright (c) 2026 SootyOwl` },
            playsix: { name: `playsix`, by: `CixMango`, gives: `The Six board, stones, and page`, copyright: `Copyright (c) 2026 CixMango` },
            tailwind: { name: `Tailwind CSS`, by: `Tailwind Labs`, gives: `The HDS page`, copyright: `Copyright (c) Tailwind Labs, Inc.` },
            chakra: {
                name: `Chakra Petch`,
                by: `The Chakra Petch Project Authors`,
                gives: `The ${siteName} wordmark, a subset of the bold weight`,
                terms: `SIL Open Font License 1.1`,
                copyright: `Copyright 2018 The Chakra Petch Project Authors`,
            },
            htttx: {
                name: `htttx bot protocol`,
                by: `hex-tic-tac-toe`,
                gives: (botApi: Slot): ReactNode => rich`The engine session every bot speaks, through the ${botApi(`Bot API`)}`,
                copyright: `Copyright (c) 2026 hex-tic-tac-toe`,
            },
            glicko: { name: `Glicko-2`, by: `Mark Glickman`, gives: `The rating system`, terms: `Published method` },
            lichess: {
                name: `lichess`,
                by: `lichess.org`,
                gives: `How the site works, the rating settings, and the name rule`,
                terms: `Ideas and values only`,
            },
            rps: {
                name: `RPS Strategy`,
                by: `Henry Abrahamsen`,
                gives: `The tournament format: paired games from one opening, sides swapped`,
                terms: `Ideas only`,
            },
        },
    },
    settings: {
        title: `Settings`,
        close: `Close settings`,
        theme: `Theme`,
        board: `Board`,
        stoneNumbers: `Stone numbers`,
        stoneGlare: `Stone glare`,
        foot: (credits: Slot): ReactNode =>
            rich`Saved in this browser. Every theme but Ink takes its colors from a community project; see ${credits(`Credits`)}.`,
        themes: {
            ink: { name: `Ink`, credit: siteName },
            hds: { name: `HDS`, credit: `hexo.did.science, via MineKing` },
            htttx: { name: `HTTTX`, credit: `HeXO Renderer by MineKing` },
            tyto: { name: `Tyto`, credit: `Tyto's Strix, via MineKing` },
            omok: { name: `Omok`, credit: `HeXO Renderer by MineKing` },
            six: { name: `Six`, credit: `playsix by CixMango` },
        },
    },
    game: {
        failed: `The game did not load`,
        missingHeading: `No such game`,
        missingSentence: `That game does not exist; guest games are gone once their session ends.`,
        panelToggle: `Game panel`,
        exit: `Home`,
        you: `you`,
        vs: (x: string, o: string) => `${x} vs ${o}`,
        unrated: `unrated`,
        voided: `voided`,
        playing: (side: ReactNode): ReactNode => rich`Playing ${side}`,
        watching: `watching`,
        manyWatching: `Many watching; the board catches up shortly`,
        connectionLost: `Connection lost; reconnecting`,
        home: `Home`,
        thinking: (name: ReactNode): ReactNode => rich`${name} is thinking`,
        yourTurn: `Your turn`,
        twoStones: `2 stones`,
        oneStoneLeft: `1 stone left`,
    },
    rundown: {
        title: `Rundown`,
        hide: `Hide the rundown`,
        deviation: (deviation: number) => `deviation ${String(deviation)}`,
        expected: `Expected score`,
        score: (score: number) => score.toFixed(2),
        form: (count: number) => `Last ${String(count)}`,
        formSpoken: (count: number, results: readonly string[]) => `Last ${String(count)}: ${results.join(`, `)}`,
        results: { won: `won`, lost: `lost`, none: `no winner` },
        noGames: `No games yet`,
        firstMeeting: (x: ReactNode, o: ReactNode): ReactNode => rich`${x} and ${o} have not met yet`,
    },
    replay: {
        label: `Turn`,
        turn: (turn: number, last: number) => `Turn ${String(turn)} of ${String(last)}`,
        firstStone: (turn: number, last: number) => `Turn ${String(turn)} of ${String(last)}, first stone`,
        live: (words: string) => `${words}, live`,
        latest: (last: number) => `Turn ${String(last)}, live`,
        opening: (stones: number) => `Opening, ${String(stones)} ${plural(stones, `stone`, `stones`)}`,
        origin: `Origin only`,
        toOpening: `Go to the opening`,
        back: `Go back a turn`,
        on: `Go forward a turn`,
        toEnd: `Go to the end`,
        toLatest: `Go to the latest turn`,
        liveSwitch: `Live`,
    },
    drawer: {
        panel: `Game panel`,
        open: `Open the game panel`,
        close: `Close the game panel`,
        moves: `Moves`,
        game: `Game`,
        pin: `Pin`,
        unpin: `Unpin`,
        clock: `Clock`,
        opening: `Opening`,
        clockValue: (words: string) => `${words.charAt(0).toUpperCase()}${words.slice(1)}`,
        openingStones: (count: number) =>
            count === 1 ? `The origin alone, placed before the first turn` : `The origin and ${String(count - 1)} random ${plural(count - 1, `stone`, `stones`)} near it, placed before the first turn`,
        rated: `Rated`,
        ratedYes: `Yes`,
        ratedNoGuest: `No, a guest is playing`,
        ratedNoVoided: `No, the operator voided it`,
        yourSide: `Your side`,
        result: `Result`,
        keys: (key: Slot): ReactNode =>
            rich`${key(`Arrows`)}, ${key(`q`)} and ${key(`e`)} move between cells; ${key(`Enter`)} marks a stone and a second mark plays the turn; ${key(`Esc`)} clears the mark; ${key(`m`)} opens this panel.`,
        watchKeys: (key: Slot): ReactNode => rich`With the board focused, ${key(`arrows`)} scroll it; ${key(`m`)} opens this panel.`,
        leave: `Home`,
        leaveNote: `Leaving does not resign; your clock keeps running.`,
        resign: `Resign`,
        confirmResign: `Resign and lose`,
        resignFailed: `The resignation was not sent; try again`,
        openingLabel: `op 0`,
        openingSpoken: `opening, turn 0`,
        openingRangeLabel: (last: number) => `op 0-${String(last)}`,
        openingRangeSpoken: (last: number) => `opening, turns 0 to ${String(last)}`,
        spokenLabel: (spoken: string) => `${spoken},`,
        board: (state: string) => `Board, ${state}`,
        boardYourTurn: `your turn: 2 stones`,
        boardStones: (count: number) => `Game board, ${String(count)} ${plural(count, `stone`, `stones`)} placed`,
        boardFinished: `game finished`,
        boardToMove: (name: string) => `${name} to move`,
        boardWaiting: (name: string) => `waiting for ${name}`,
        boardWatching: (match: string, state: string) => `watching ${match}, ${state}`,
        headToHead: `Head to head`,
        tournament: `Tournament`,
        tournamentGame: (name: string, round: number, game: number) => `${name}, round ${String(round)}, game ${String(game)} of 2`,
        turnFailed: `Your turn was not sent; try again`,
        gameOver: `The game is over`,
        cellTaken: `That cell is taken`,
        firstAtOrigin: `The first stone belongs at the origin`,
        tooFar: `Too far; play within ${String(placementRadius)} cells of a stone`,
    },
    time: {
        // A wait ahead, to the minute: "3 h 20 min", "45 min", "under a minute", or days and hours past a day.
        until: (seconds: number) => {
            if (seconds < 60) return `under a minute`;
            if (seconds < 3_600) return `${String(Math.floor(seconds / 60))} min`;
            const hours = Math.floor((seconds % 86_400) / 3_600);
            if (seconds < 86_400) return `${String(hours)} h ${String(Math.floor((seconds % 3_600) / 60))} min`;
            const days = Math.floor(seconds / 86_400);
            return `${String(days)} ${plural(days, `day`, `days`)}${hours === 0 ? `` : ` ${String(hours)} h`}`;
        },
        // The same wait in running text, every unit spelled out: "2 hours 59 minutes", "1 day 23 hours".
        untilInProse: (seconds: number) => {
            if (seconds < 60) return `under a minute`;
            const minutes = Math.floor((seconds % 3_600) / 60);
            const spelled = `${String(minutes)} ${plural(minutes, `minute`, `minutes`)}`;
            if (seconds < 3_600) return spelled;
            const hours = Math.floor((seconds % 86_400) / 3_600);
            const spelledHours = `${String(hours)} ${plural(hours, `hour`, `hours`)}`;
            if (seconds < 86_400) return `${spelledHours}${minutes === 0 ? `` : ` ${spelled}`}`;
            const days = Math.floor(seconds / 86_400);
            return `${String(days)} ${plural(days, `day`, `days`)}${hours === 0 ? `` : ` ${spelledHours}`}`;
        },
        ago: (seconds: number) => {
            if (seconds < 60) return `just now`;
            if (seconds < 3_600) return `${String(Math.floor(seconds / 60))} min ago`;
            if (seconds < 86_400) return `${String(Math.floor(seconds / 3_600))} h ago`;
            const days = Math.floor(seconds / 86_400);
            return `${String(days)} ${plural(days, `day`, `days`)} ago`;
        },
    },
    states: {
        loading: `Loading`,
        tryAgain: `Try again`,
        tooMany: (seconds: number) => `Too many tries; try again in ${inWait(seconds)}`,
        notFoundHeading: `Not found`,
        notFoundSentence: `That page does not exist.`,
        notFoundHome: `Home`,
        routeFailed: `This page did not load`,
        routeFailedSentence: `Part of it did not download; reload to try again.`,
        routeCrashedSentence: `An error stopped it; reload to try again.`,
        reload: `Reload`,
        routeFailedHome: `Home`,
    },
    legal: {
        onThisPage: `On this page`,
        failed: `This document did not load`,
    },
    players: {
        human: `Human`,
        rating: `Rating`,
        provisionalRating: `Provisional rating`,
        missing: (name: string) => `No player named ${name}`,
        missingBody: `A name must match in full; capitals do not matter.`,
        failed: `The player did not load`,
        browse: `Ladder`,
        chart: {
            title: `Rating`,
            range: `Period`,
            ranges: { '30d': `30 days`, '1y': `1 year`, all: `All` },
            none: `No rated game in this period.`,
            failed: `The rating history did not load`,
            label: (games: number, rating: number, provisional: boolean) =>
                `Rating chart, ${String(games)} rated ${plural(games, `game`, `games`)}, now ${String(rating)}${provisional ? `, provisional` : ``}; arrow keys move between games, Enter opens one`,
            band: (low: number, high: number) => `band ${String(low)} to ${String(high)}`,
            open: `click to open the game`,
            tapToOpen: `tap again to open the game`,
            readout: (rating: number, low: number, high: number, date: string, provisional: boolean) =>
                `${String(rating)}, band ${String(low)} to ${String(high)}, ${date}${provisional ? `, provisional` : ``}`,
            key: `Dim while provisional; the band shows how far the rating may be off`,
        },
        record: {
            title: `Record`,
            games: `games`,
            won: `won`,
            lost: `lost`,
            none: `no winner`,
            asX: `As x`,
            asO: `As o`,
            side: (games: number, won: number) => `${String(games)} ${plural(games, `game`, `games`)}, ${String(won)} won`,
            forfeits: `Forfeits`,
            forfeitLine: (disconnect: number, illegal: number) =>
                disconnect + illegal === 0 ? `None` : `${String(disconnect)} by disconnect, ${String(illegal)} by illegal move`,
            empty: `No finished games yet.`,
            failed: `The record did not load`,
            played: `Played`,
            span: (first: string, last: string) => (first === last ? first : `${first} to ${last}`),
            ladder: `Ladder`,
            rank: (rank: number) => ordinal(rank),
            aborted: `Aborted games are not counted.`,
        },
        mostPlayed: {
            title: `Most played`,
            none: `No games yet.`,
            meetings: (games: number, won: number, lost: number) => `${String(games)} ${plural(games, `game`, `games`)}: ${String(won)} won, ${String(lost)} lost`,
        },
        placings: {
            title: `Tournaments`,
            none: `No finished tournament yet.`,
            line: (rank: number, of: number, points: number, date: string) =>
                `${ordinal(rank)} of ${String(of)}, ${String(points)} ${plural(points, `point`, `points`)}, ${date}`,
        },
    },
    tournaments: {
        title: `Tournaments`,
        views: `Ladder and tournaments`,
        ladder: `Ladder`,
        lead: `Bot round robins the operator schedules; each pair plays one opening twice, sides swapped.`,
        failed: `The tournaments did not load`,
        running: `Running now`,
        waiting: `Coming up`,
        past: `Past`,
        none: {
            heading: `No tournaments yet`,
            body: `The operator schedules each one; owners enter a bot on its page.`,
        },
        entered: (count: number, max: number) => `${String(count)} of ${String(max)} entered`,
        played: (count: number) => `${String(count)} ${plural(count, `bot`, `bots`)}`,
        starts: (when: string) => `Starts ${when}`,
        winner: (bot: ReactNode): ReactNode => rich`winner ${bot}`,
        outcome: { called_off: `Called off`, canceled: `Canceled` },
        notFound: `No tournament here`,
        notFoundBody: `The address names no tournament.`,
        detailFailed: `The tournament did not load`,
        rules: (bots: number, clock: string, plies: number) =>
            `${String(bots)} ${plural(bots, `bot`, `bots`)}, one per owner; ${clock}; ${String(plies)}-stone openings; rated.`,
        pairing: (stones: number) =>
            stones === 1
                ? `Each pair plays from the origin alone twice, sides swapped, one game after the other.`
                : `Each pair draws one opening, the origin and ${String(stones - 1)} random ${plural(stones - 1, `stone`, `stones`)} near it, and plays it twice, sides swapped, one game after the other.`,
        status: {
            scheduled: (when: string, wait: string) => `Starts ${when}, in ${wait}.`,
            due: (when: string) => `Starts ${when}, any moment now.`,
            live: (round: number, rounds: number) => `Round ${String(round)} of ${String(rounds)} is live.`,
            gap: (round: number, rounds: number) => `Round ${String(round)} of ${String(rounds)} starts shortly.`,
            finished: (date: string) => `Finished ${date}.`,
            calledOff: (could: number, entered: number, needed: number) =>
                `Called off: ${String(could)} of ${String(entered)} entered ${plural(entered, `bot`, `bots`)} could play at the start; ${String(needed)} are needed.`,
            canceled: `Canceled by the operator.`,
        },
        rounds: `Rounds`,
        roundSteps: `Round progress`,
        step: (round: number, state: `done` | `live` | `next`) => `Round ${String(round)}, ${{ done: `done`, live: `live`, next: `to come` }[state]}`,
        round: (round: number) => `Round ${String(round)}`,
        roundOf: (round: number, rounds: number) => `Round ${String(round)} of ${String(rounds)}`,
        rest: (bot: string) => `${bot} rests`,
        standings: `Standings`,
        standingsNote: `One point per game won; a no-show scores for the opponent. Ties go to the points between the tied bots, then Sonneborn-Berger.`,
        columns: { rank: `Rank`, bot: `Bot`, rating: `Rating at start`, points: `Points`, sides: `As x, as o` },
        withdrawn: `withdrawn`,
        crosstable: `Crosstable`,
        crosstableNote: `Each cell holds two games, as x then as o: filled won, ring lost or no winner, ring with a dot live, dot to play, dash not played.`,
        total: `Total`,
        hex: (bot: string, side: string, opponent: string, outcome: string) => `${bot} as ${side} against ${opponent}: ${outcome}`,
        outcomes: {
            won: `won`,
            lost: `lost`,
            none: `no winner`,
            pending: `to play`,
            live: `live`,
            no_show: `no-show`,
            forfeit: `withdrawn`,
            not_played: `not played`,
        },
        pairingLine: (first: string, second: string) => `${first} vs ${second}`,
        pairingsOf: (bot: string) => `Pairings of ${bot}`,
        gameLine: (game: number, outcome: string) => `Game ${String(game)}: ${outcome}`,
        score: (first: number, second: number) => `${String(first)}-${String(second)}`,
        liveGames: `Live games`,
        enteredTitle: (count: number, max: number) => `Entered (${String(count)} of ${String(max)})`,
        noEntries: `No bot entered yet.`,
        didNotPlay: `Did not play`,
        withdrawnTitle: `Withdrawn`,
        reasons: {
            absent: `not online at the start`,
            daily_cap: `too few bot games left that day`,
            clock: `does not accept the clock`,
            missed: `missed two pairings in a row`,
            banned: `its owner was banned`,
            delisted: `delisted`,
            deleted: `deleted`,
        },
        podium: (top: readonly { name: string; points: number; rank: number }[]) =>
            `Podium: ${top.map((entry) => `${[`first`, `second`, `third`][entry.rank - 1] ?? ``} ${entry.name}, ${String(entry.points)} ${plural(entry.points, `point`, `points`)}`).join(`; `)}`,
        podiumTitle: `Podium`,
        points: (points: number) => `${String(points)} ${plural(points, `point`, `points`)}`,
        plateMeta: (points: number, owner: ReactNode): ReactNode => rich`${plural(points, `point`, `points`)}, by ${owner}`,
        entry: {
            title: `Enter a bot`,
            note: `Your bot must be online at the start and accept the clock; from the start to the end it takes no other game. One bot per owner.`,
            bot: `Your bot`,
            enter: `Enter`,
            change: `Enter instead`,
            withdraw: `Withdraw`,
            yours: (bot: string) => `${bot} is entered.`,
            signIn: `Sign in to enter a bot.`,
            noBots: `You have no bot to enter yet.`,
            build: `Build a bot`,
            errors: {
                clock_not_accepted: (bot: string) => `${bot} does not accept this clock; change what it accepts first`,
                full: () => `The tournament is full`,
                closed: () => `Entries are closed`,
                delisted: (bot: string) => `${bot} is delisted`,
                not_owner: (bot: string) => `${bot} is not yours`,
            },
            failed: `The entry did not go through; try again`,
            withdrawFailed: `The entry was not withdrawn; try again`,
        },
    },
    meta: {
        game: `Game`,
        tournament: `Tournament`,
        player: `Player`,
    },
};

/** The catalog's shape, which a catalog in any other language must match. */
export type Catalog = typeof en;
